#include "datetime.dl"

.decl Times(timestamp:timestamp)
.decl Test(operator:symbol, timestamp:timestamp, result:symbol)

Times(@from_date("1970-01-01")) :- true.
Times(@from_date("1970-01-02")) :- true.
Times(@now()) :- true.
 
Test("@to_day", timestamp, to_string(@to_day(timestamp))) :- Times(timestamp).
Test("@to_date", timestamp, @to_date(timestamp)) :- Times(timestamp).
Test("@to_date_time", timestamp, @to_date_time(timestamp)) :- Times(timestamp).
Test("@age", timestamp1, to_string(@age(timestamp1,timestamp2))) :- 
    Times(timestamp1), Times(timestamp2), timestamp1<timestamp2.

.output Test
